### ISSUE TITLE
[Task] Add the mongo service in the docker-compose generator.

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/lenra_cli#10]
## What should be done 
We should add the mongo service to be compatible with the Mongo data system.
Also, fix the Env restart commande that have changed.

## Technical recommandation
I've updated the `docker-compose.yml` file to add the mongo service. 
The service : 
```yml
  mongodb:
    image: mongo:5.0.11-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test
      CONFIG: '{"_id" : "rs0", "members" : [{"_id" : 0,"host" : "mongodb:27017"}]}'
    healthcheck:
      test: test $$(echo "rs.initiate($$CONFIG).ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 5s
      start_period: 10s
      retries: 5
    command: mongod --replSet rs0
```

Add the environment variable for the devtool service : 
```yml
environment:
    MONGO_URL: mongodb://mongodb:27017
```

Then add the dependancy for the devtool service : 
```yml
    depends_on:
      mongodb:
        condition: service_healthy
```

Finally change command that stop the env to : 
```
ApplicationRunner.Environment.DynamicSupervisor.stop_env(1) 
```
