### ISSUE TITLE
[Task] Define app memory limit

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/lenra_cli#125]
## What should be done 
Define is the Docker Compose file the app memory limit in the Docker Compose file with the same memory limit defined by the Lenra server.

## Technical recommandation

```
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
```
