### ISSUE TITLE
[Bug]: Add possibility to define platform on `lenra dev`

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/lenra_cli#413]
### What happened?

When trying to run an application locally using `lenra dev` on MacOS and when the application is using a reference image only compiled in `linux/amd64` I get an error telling me that my platform is not recognised when running the app.

When specifying by hand that I want to use this image using `linux/amd64` it works.

We might need to add a way to specify the platform to use.
A better solution to begin with would be to use `linux/amd64` by default, forcing all devices to emulate for this platform.

**Comment by taorepoara** [comment]
To resolve this we can define in the `dev` part the platform for each service. Here is an example:

```
generator:
...
dev:
  devtool:
    platform: linux/amd64
  mongo:
    platform: linux/arm64/v8
```
